name: portalpong
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  avatars: ^3.0.2
  faker: ^2.0.0
  flame_forge2d: ^0.8.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  json_annotation: ^4.4.0
  network_info_plus: ^2.1.3
  shared_preferences: ^2.0.13
  shelf_web_socket: ^1.0.1
  uuid: ^3.0.6
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
